.TH QTSYNCR "1" "Juli 2018" "0.1.0" "User Commands"
.SH NAME
QtSyncR

.SH SYNOPSIS
.B QtSyncR
.br
.B QtSyncR
[\-f|\-\-file ...]

.SH DESCRIPTION
.B QtSyncR
A graphical utiltiy for synchronizing files and folders.

.SH OPTIONS
.TP
\fB\-f, \-\-file <file>\fR
Don't open GUI. Run the given profile file.

.SH COPYRIGHT
Copyright 2018 Julian Bansen, jsbansen@mailbox.org
.PP
This program is licensed under the MIT license. It is provided "as-is", without warranty of any kind. In no event shall the author be held liable for any damage caused by this program.